---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mgkvvytn/public_html/
    - /bin/npm install
    - /bin/npm run build
    - /bin/cp -R .output/* $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH/ # Optional: if you need your env variables