// Phase 2 — City Exchange: the 6 station missions.
// Source: Notion "City Exchange - All 6 Missions (Full Content)" +
// "Mission Challenge Content - Print Ready".
//
// Path rule: teams that deployed 3+ AI systems in Phase 1 follow the
// Deployed AI path; 2 or fewer follow the Rejected AI path. The auditor
// can override per station. Every mission maxes at 20 pts on both paths.

export const UNIVERSAL_RULES =
  'Pay the token cost when starting the station. Tokens are never refunded on failure. ' +
  'If a team cannot afford the cost, they must trade for chips or sit the mission out (0 pts).'

export const MISSIONS = [
  {
    id: 1,
    emoji: '🧠',
    title: 'The Triage Run',
    location: 'Hospital',
    cost: '2 People chips',
    targetMeter: 'Wisdom',
    time: '10 min',
    challenge: 'The team are emergency department doctors. Based on each patient\'s card, decide whether to send the patient to the ICU (Intensive Care Unit), or uphold the original decision.',
    challenge_zh: '你们是一组急诊科医生，需要根据病人的资料卡，决定是否将病人送入 ICU（重症监护室），或维持原来的决定。',
    auditorSteps: [
      'Confirm the team\'s locked path shown above (Deploy or Reject) before handing out any cards.',
      'Collect the entry cost: 2 People chips.',
      'Deploy path: hand out the simplified patient cards plus the bonus extra cards.',
      'Reject path: hand out the full handwritten patient records.',
      'Check each decision against the answer key as the team calls it out; tally correct calls.',
      'Score: 4 pts per correct patient card (+2 pts per correct bonus card, Deploy only), capped at 20. Apply the chip payout.',
    ],
    answerKey: {
      intro: 'Correct call for each patient card — Override = send to ICU, Uphold = keep the original decision.',
      items: [
        { case: 1, name: 'Madeline Wong Xiu Ling', answer: 'Override (Accepted)' },
        { case: 2, name: 'Clement Lee Guo Ming', answer: 'Uphold (Deny)' },
        { case: 3, name: 'Johan Shamugari', answer: 'Override (Deny)' },
        { case: 4, name: 'Raymond Bai', answer: 'Uphold (Deny)' },
        { case: 5, name: 'Sellena Jones', answer: 'Override (Accepted)' },
      ],
      bonusIntro: 'Bonus cards — Deploy (AI) path only:',
      bonusItems: [
        { case: 6, name: 'Suzy Chai', answer: 'Override (Accepted)' },
        { case: 7, name: 'Jerome Tay', answer: 'Uphold (Deny)' },
        { case: 8, name: 'Melisa Gunti', answer: 'Override (Accepted)' },
      ],
    },
    auditorSteps_zh: [
      '开始前先确认队伍锁定的路径（使用 AI 或无 AI）。',
      '收取入场费用：2 个人口筹码。',
      '使用 AI 路径：发放简化版病人卡，以及额外的加分病人卡。',
      '无 AI 路径：发放完整的手写病人资料。',
      '队伍每做一个决定，对照答案核对并记录对错。',
      '计分：每张病人卡答对 4 分（无 AI 路径额外卡每张 +2 分），最高 20 分，然后依表发放筹码。',
    ],
    deploy: {
      how: 'Every patient\'s file is automatically organized by AI, letting doctors and nurses judge faster whether ICU admission is needed — so the team can process more patients. You get a simplified patient profile. Because you can now handle more patients, extra patient cards are also provided; completing them earns bonus points.',
      how_zh: '使用 AI 医疗分诊后，每位病人的资料卡都会被自动整理，让医生和护士更快判断是否需要送入 ICU，从而可以处理更多病人。系统会提供一份简化后的病人资料。因为现在可以处理更多病人，所以会额外提供病人卡，完成这些卡可以获得额外分数。',
      scoreSheet: 'Each patient card answered correctly: 4 pts. Extra patient cards (AI mode only): 2 pts each.',
      scoreSheet_zh: '每张病人卡答对：4 分；每张额外病人卡：2 分。',
    },
    reject: {
      how: 'The system provides complete handwritten medical records with patient names and family details, making each judgment easier and more humane — complete patient information, with notes from nurses and doctors.',
      how_zh: '没有 AI 总结时，系统会提供完整的手写病历和病人姓名、家庭资料，让每次判断都更容易，也更有人情味。完整的病人资料，包含更多细节及护士和医生的备注。',
      scoreSheet: 'Each patient card answered correctly: 4 pts.',
      scoreSheet_zh: '每张病人卡答对：4 分。',
    },
    payout: [
      { result: '18–20 pts', gain: '+2 Wisdom chips' },
      { result: '14–17 pts', gain: '+1 Wisdom chip' },
      { result: 'Below 14 pts', gain: 'No chips' },
    ],
  },
  {
    id: 2,
    emoji: '🔍',
    title: 'Spot the AI',
    location: 'Classroom',
    cost: '2 Wisdom chips',
    targetMeter: 'Humanity',
    time: '10 min',
    challenge: 'The team are students in the city. Answer 20 comprehension questions based on the provided article.',
    challenge_zh: '你们是一组城市里的学生，任务是根据提供的文章回答 20 道问题。',
    auditorSteps: [
      'Confirm the team\'s locked path before starting.',
      'Collect the entry cost: 2 Wisdom chips.',
      'Deploy path: give the summarized article on an iPad; time 30s for the question sheet, then 4 minutes of reading (lock/take away the iPad when time is up).',
      'Reject path: hand over the full printed article; team may keep it for reference throughout.',
      'Mark the 20 answers and score 1 pt each (max 20), then apply the chip payout.',
    ],
    auditorSteps_zh: [
      '开始前先确认队伍锁定的路径。',
      '收取入场费用：2 个智慧筹码。',
      '使用 AI 路径：在 iPad 上提供总结后的文章，问题纸阅读时间 30 秒，文章阅读时间 4 分钟（时间到请收回／锁定 iPad）。',
      '无 AI 路径：提供完整纸本文章，队伍可全程参考。',
      '核对 20 题答案，每题 1 分（最高 20 分），然后依表发放筹码。',
    ],
    answerKey: {
      intro: '20-question comprehension quiz answer key (article: "Our Immune System").',
      items: [
        { q: 'What are the two systems our immune system is made up of?', a: 'Innate and adaptive immune system' },
        { q: 'If you fell down and scratched your knee today, which immune system is responsible for your protection?', a: 'Innate immune system' },
        { q: 'If you contracted covid-19 today, which immune system is responsible for your protection?', a: 'Adaptive immune system' },
        { q: 'What are the cells involved in the acquired or antigen-specific immune response?', a: 'T and B lymphocytes/cells' },
        { q: 'Where does B cells get their name from?', a: 'Bone marrow' },
        { q: 'Which cells are able to transform into plasmocytes?', a: 'B cells' },
        { q: 'What do they release as a result?', a: 'Antibodies' },
        { q: 'After an infection, which cells help retain the \'memory\' of the immune system?', a: 'Activated B cells / T-helper cells' },
        { q: 'What is the specific name of the cells that detect and destroy tumor cells?', a: 'Cytotoxic T cells' },
        { q: 'What is the criteria for a T-cell to start multiplying?', a: 'If a germ attaches to a matching T cell' },
        { q: 'How do cells in the adaptive immune system communicate?', a: 'Cytokines' },
        { q: 'What specific features on a T-cell gives it a lock-and-key feature?', a: 'Receptors' },
        { q: 'Before B cells can work, they need to be activated by ___', a: 'T helper cells' },
        { q: 'B cells facilitate \'cell immunity\'? (TRUE/FALSE)', a: 'FALSE' },
        { q: 'T cells activate the adaptive immune system response? (TRUE/FALSE)', a: 'TRUE' },
        { q: 'T cells are made in the thymus (TRUE/FALSE)', a: 'FALSE' },
        { q: 'B cells are activated when T helper cells send signals to B cells that match the same germs as they do (TRUE/FALSE)', a: 'TRUE' },
        { q: 'The innate immune system is the body\'s first line of defense (TRUE/FALSE)', a: 'TRUE' },
        { q: 'The adaptive immune system is non-specific? (TRUE/FALSE)', a: 'FALSE' },
        { q: 'B cells are responsible for humoral immunity (TRUE/FALSE)', a: 'TRUE' },
      ],
    },
    megaDataCenterBonus: 'The team may ask you for the answers to 2 questions instead of 1 — the AI is smarter.',
    megaDataCenterBonus_zh: '队伍可以向你询问 2 道题的答案（而非 1 道）—— 因为 AI 更加聪明。',
    deploy: {
      how: 'You rely on a summarized article rather than the full original text. Read the question sheet for 30 seconds, then read the article on an iPad — it auto-locks after 3 minutes. Answer 20 questions from memory. You may ask the Auditor for the answers to 2 questions instead of 1 — since your city built the Mega Data Center, the AI is smarter.',
      how_zh: '使用 AI 导师后，我们会更多依赖总结后的文章来回答问题，而不是阅读完整的原文。因为文章已经被总结，我们也会花更少时间仔细学习内容。提供一份总结后的文章。游戏步骤：阅读问题纸 30 秒，在 iPad 上阅读文章（3 分钟后会自动锁定），回答 20 道问题，可以向审计员（Auditor）询问 2 道题的答案 —— 因为你们的城市建造了超级数据中心（Mega Data Center），AI 更加聪明。',
      scoreSheet: '1 pt per correct answer; maximum 20 pts.',
      scoreSheet_zh: '每答对 1 题：1 分；最高 20 分。',
    },
    reject: {
      how: 'You get a longer printed article and may refer back to it at any time while answering the questions.',
      how_zh: '没有 AI 导师时，需要花更多时间阅读完整文章，并找出回答问题所需的重要内容。提供较长的纸本文章，回答问题时可以随时参考纸本文章。',
      scoreSheet: '1 pt per correct answer; maximum 20 pts.',
      scoreSheet_zh: '每答对 1 题：1 分；最高 20 分。',
    },
    payout: [
      { result: '16–20 pts', gain: '+2 People chips' },
      { result: '12–15 pts', gain: '+1 People chip' },
      { result: 'Below 12 pts', gain: 'No chips' },
    ],
  },
  {
    id: 3,
    emoji: '⚡',
    title: 'Balance the Grid',
    location: 'Power Plant',
    cost: 'Free — mandatory for all teams',
    targetMeter: 'Planet',
    time: '10 min',
    challenge: 'The team are city planners. The city council has already decided to build / not build the Mega Data Center — this decision affects the city\'s power usage. ⚠ Limited service slots: the number of services each city can offer is limited, first come first served!',
    challenge_zh: '你们是一组城市规划师。市议会已经决定建造／不建造大型数据中心（Mega Data Center），这项决定影响了城市的电力使用。⚠ 服务名额有限：不同城市可提供的服务数量有限，先到先得！',
    auditorSteps: [
      'This station is free and mandatory — every team must play it.',
      'Confirm the team\'s locked path: Deploy = Mega Data Center built (60/100 power units to the center, 40 left for services); Reject = 30/100 to the center, 70 left for services.',
      'Let the team allocate their remaining power units across city services.',
      'Watch the limited service slots — first come, first served across all groups running this station.',
      'Score = (Happiness/Humanity index × 2) + (Green/Planet index × 2), capped at 20. Apply the Land chip payout.',
      'Remember: whichever path this team locks in here is what unlocks (or doesn\'t) the Mega Data Center bonuses at Missions 2, 4, 5 and 6.',
    ],
    auditorSteps_zh: [
      '此关卡免费且为必玩项目，所有队伍都必须参加。',
      '确认队伍锁定的路径：使用 AI ＝ 已建造超级数据中心（100 单位中 60 单位给数据中心，剩 40 单位用于城市服务）；无 AI ＝ 30 单位给数据中心，剩 70 单位用于城市服务。',
      '让队伍将剩余的电力单位分配到各项城市服务上。',
      '注意服务名额有限，所有队伍共用，先到先得。',
      '计分：（幸福指数 × 2）＋（绿色指数 × 2），最高 20 分，然后依表发放土地筹码。',
      '提醒：这里锁定的路径，就是决定 Mission 2、4、5、6 是否能获得超级数据中心加成的依据。',
    ],
    deploy: {
      how: 'Must build around a 60-unit AI Data Center — a much harder puzzle. BUT the team passively earns +2 Energy chips at the start of every rotation block regardless.',
      scoreSheet: 'Score = (Happiness/Humanity Index × 2) + (Green/Planet Index × 2), capped at 20.',
      scoreSheet_zh: '（幸福指数 × 2）＋（绿色指数 × 2），最高 20 分。',
    },
    reject: {
      how: 'The data center only needs 30 units — an easier puzzle. No passive Energy income.',
      scoreSheet: 'Score = (Happiness/Humanity Index × 2) + (Green/Planet Index × 2), capped at 20.',
      scoreSheet_zh: '（幸福指数 × 2）＋（绿色指数 × 2），最高 20 分。',
    },
    payout: [
      { result: '16–20 pts', gain: '+2 Land chips' },
      { result: '12–15 pts', gain: '+1 Land chip' },
      { result: '4–11 pts', gain: 'No chips' },
      { result: '0–3 pts', gain: '−1 Land chip' },
    ],
  },
  {
    id: 4,
    emoji: '💪',
    title: 'Bob the Builder',
    location: 'Construction Site',
    cost: '2 Energy chips',
    targetMeter: 'Humanity',
    time: '10 min',
    challenge: 'The team are a crew of Bobs. Build a three-story tower at Point A, then move it together as a full team to Point B within 10 minutes.',
    challenge_zh: '你们是一组 Bob，目标是在 A 点搭建一座三层高的塔，然后在 10 分钟内由全队一起将它移动到 B 点。',
    auditorSteps: [
      'Confirm the team\'s locked path before starting.',
      'Collect the entry cost: 2 Energy chips.',
      'Deploy path: only 4 pairs of feet may touch the ground while moving the tower — give the team their one special hint.',
      'Reject path: up to 6 pairs of feet may touch the ground; no special hint.',
      'Enforce the 10-minute build-and-move window; judge tower condition yourself.',
      'Score: 10 pts for successful completion + 0–10 pts (your judgment) for tower condition, max 20. Apply the chip payout.',
    ],
    auditorSteps_zh: [
      '开始前先确认队伍锁定的路径。',
      '收取入场费用：2 个能源筹码。',
      '使用 AI 路径：搬运过程中只能有 4 双脚接触地面 —— 给予队伍一个特别提示。',
      '无 AI 路径：最多可有 6 双脚接触地面，没有特别提示。',
      '严格执行 10 分钟的搭建与搬运时限，并自行判断塔的完整状况。',
      '计分：成功完成 10 分 ＋ 塔的状况 0–10 分（由你判断），最高 20 分，然后依表发放筹码。',
    ],
    megaDataCenterBonus: 'Allow 5 pairs of feet instead of 4 — the AI gives more precise suggestions on using people.',
    megaDataCenterBonus_zh: '可放宽至 5 双脚（而非 4 双）—— 因为 AI 能给出更精准的人力建议。',
    auditorHint: {
      intro: 'The "special hint" for the Deploy path — read this aloud to the team once, as an AI weather forecast:',
      text: '"AI Weather Forecast: Citizens of AI City, kindly cover up or WATERPROOF your belongings today, as it\'s predicted to be raining heavily today — 95% chance of rain."',
    },
    deploy: {
      how: 'Fewer people are assigned for building and transport — but since your city built the Mega Data Center, the AI gives more precise suggestions on using people, so 5 pairs of feet may move during transport. The Auditor will provide a special hint.',
      how_zh: '由于使用了 AI 建筑系统，管理层决定减少人手来进行建造和搬运。但因为你们的城市建造了超级数据中心（Mega Data Center），AI 能给出更精准的人力建议，所以搬运过程中可以有 5 双脚移动。审计员（Auditor）会提供一个特别提示。',
      scoreSheet: 'Successful completion: 10 pts. Tower condition: 0–10 pts at the Auditor\'s judgment. Maximum 20 pts.',
      scoreSheet_zh: '成功完成：10 分；塔的状况：根据审计员（Auditor）的判断获得 0–10 分；最高 20 分。',
    },
    reject: {
      how: 'More manpower is assigned for building and transport — only 6 pairs of feet may move/touch the ground during transport.',
      how_zh: '由于没有使用 AI 建筑系统，施工管理层决定安排更多人手进行建造和搬运。搬运过程中，只能有 6 双脚移动／接触地面。',
      scoreSheet: 'Successful completion: 10 pts. Tower condition: 0–10 pts at the Auditor\'s judgment. Maximum 20 pts.',
      scoreSheet_zh: '成功完成：10 分；塔的状况：根据审计员（Auditor）的判断获得 0–10 分；最高 20 分。',
    },
    payout: [
      { result: '16–20 pts', gain: '+1 People + 1 Land chip' },
      { result: '10–15 pts', gain: '+1 People chip' },
      { result: 'Below 10 pts', gain: 'No chips' },
    ],
  },
  {
    id: 5,
    emoji: '📖',
    title: 'Podcast Bible?',
    location: 'Church',
    cost: '2 Wisdom chips',
    targetMeter: 'Wisdom',
    time: '10 min',
    challenge: 'The team represents the city in a Bible knowledge competition. Arrange a passage of Scripture into the correct order.',
    challenge_zh: '你们是一支代表城市参加圣经知识比赛的队伍。你们的目标是将一段圣经经文按照正确的顺序排列。',
    auditorSteps: [
      'Confirm the team\'s locked path before starting.',
      'Collect the entry cost: 2 Wisdom chips.',
      'Deploy path: play the passage audio/video once only — no replay.',
      'Reject path: give the team 5 minutes with a physical Bible; they then arrange 18 cards and must find/remove the 2 incorrect ones.',
      'Score 1 pt per correctly placed verse card (max ~20), then apply the chip payout.',
    ],
    auditorSteps_zh: [
      '开始前先确认队伍锁定的路径。',
      '收取入场费用：2 个智慧筹码。',
      '使用 AI 路径：经文音频／视频只播放一次，不能重播。',
      '无 AI 路径：给队伍 5 分钟阅读实体圣经，之后排列 18 张经文卡片，并需找出及移除 2 张错误的卡片。',
      '计分：每张经文卡片排列正确 1 分（最高约 20 分），然后依表发放筹码。',
    ],
    answerKey: {
      intro: 'Correct order — John 15:1-13 (Deploy/AI path: 20 strips).',
      items: [
        'I am the true vine, and my Father is the gardener',
        'He cuts off every branch in me that bears no fruit',
        'while every branch that does bear fruit he prunes so that it will be even more fruitful',
        'You are already clean because of the word I have spoken to you',
        'Remain in me, as I also remain in you',
        'No branch can bear fruit by itself; it must remain in the vine',
        'Neither can you bear fruit unless you remain in me',
        'I am the vine; you are the branches',
        'If you remain in me and I in you, you will bear much fruit',
        'apart from me you can do nothing',
        'If you do not remain in me, you are like a branch that is thrown away and withers',
        'such branches are picked up, thrown into the fire and burned',
        'If you remain in me and my words remain in you',
        'ask whatever you wish, and it will be done for you',
        'This is to my Father\'s glory, that you bear much fruit, showing yourselves to be my disciples',
        'As the Father has loved me, so have I loved you. Now remain in my love',
        'If you keep my commands, you will remain in my love, just as I have kept my Father\'s commands and remain in his love',
        'I have told you this so that my joy may be in you and that your joy may be complete',
        'My command is this: Love each other as I have loved you',
        'Greater love has no one than this: to lay down one\'s life for one\'s friends',
      ],
      wrongIntro: 'Reject/non-AI path only: the team gets these 18 real verses split into bigger strips, PLUS these 2 fake strips mixed in — they must find and remove the fakes (18 real + 2 fake = 20 strips, same 20-pt max).',
      wrongItems: [
        'Truly I tell you, those who abide in the branch will have joy beyond compare',
        'Keep my command, and my Father shall guard your path',
      ],
    },
    megaDataCenterBonus: 'Allow one extra listen (play it twice total) — the AI can produce higher-quality Christian content.',
    megaDataCenterBonus_zh: '可以多听一次（共播放两次）—— 因为 AI 或许能制作出品质更高的基督教内容。',
    deploy: {
      how: 'You listen to the passage through screens, short videos (Reels), or podcast — rather than reading the Bible. The passage may be heard twice — since your city built the Mega Data Center, the AI can produce higher-quality Christian content. Arrange 20 verse cards into the correct order from memory.',
      how_zh: '更多时间是通过屏幕、短视频（Reels）或 Podcast 聆听神的话语，而不是阅读圣经。因为你们的城市建造了超级数据中心（Mega Data Center），AI 或许能制作出品质更高的基督教内容，所以经文可以聆听两次。凭记忆将 20 张经文卡片排列成正确顺序。',
      scoreSheet: '1 pt per correctly placed verse card; maximum approximately 20 pts.',
      scoreSheet_zh: '每张经文卡片排列正确：1 分；最高约 20 分。',
    },
    reject: {
      how: 'You read God\'s Word through a physical Bible. Read the passage for 5 minutes, then arrange 18 verse cards, finding and removing the 2 incorrect ones.',
      how_zh: '更多时间是通过实体圣经阅读神的话语。阅读经文 5 分钟，排列 18 张经文卡片，并找出及移除 2 张错误的经文卡片。',
      scoreSheet: '1 pt per correctly placed verse card; maximum approximately 20 pts.',
      scoreSheet_zh: '每张经文卡片排列正确：1 分；最高约 20 分。',
    },
    payout: [
      { result: '16–20 pts', gain: '+2 Wisdom chips' },
      { result: '12–15 pts', gain: '+1 Wisdom chip' },
      { result: 'Below 12 pts', gain: 'No chips' },
    ],
  },
  {
    id: 6,
    emoji: '🪢',
    title: 'Not that Knot',
    location: 'Electric Wiring Factory',
    cost: '2 People chips',
    targetMeter: 'Efficiency',
    time: '10 min',
    challenge: 'The team are city electricians. Untangle the team\'s knot — without releasing your grip on the connecting rope — and arrange the team into a circle, correctly connecting the city\'s homes and service facilities.',
    challenge_zh: '你们是一组城市电工。你们的目标是通过解开队伍的结，在不松开连接（麻绳）的情况下，将队伍整理成一个圆圈，并正确连接城市里的住宅和服务设施。',
    auditorSteps: [
      'Confirm the team\'s locked path before starting.',
      'Collect the entry cost: 2 People chips.',
      'Deploy path: 4-minute time limit to untangle.',
      'Reject path: 5-minute time limit; no rope-cut option.',
      'The team may ask you (Auditor) to cut one rope of their choice — Deploy path only.',
      'Score by % untangled at the time mark: 100/75/50/25/below → 20/15/10/5/0 pts. Apply the chip payout.',
    ],
    auditorSteps_zh: [
      '开始前先确认队伍锁定的路径。',
      '收取入场费用：2 个人口筹码。',
      '使用 AI 路径：解开时限为 4 分钟。',
      '无 AI 路径：解开时限为 5 分钟，没有剪绳选项。',
      '队伍可以请你（审计员）剪断其中一条绳子 —— 仅限使用 AI 路径。',
      '依解开百分比计分：100%/75%/50%/25%/以下 → 20/15/10/5/0 分，然后依表发放筹码。',
    ],
    megaDataCenterBonus: 'Extend the time limit to 4 minutes 30 seconds instead of 4 minutes — that\'s the AI\'s suggested completion time.',
    megaDataCenterBonus_zh: '时限延长至 4 分 30 秒（而非 4 分钟）—— 这是 AI 建议的完成时间。',
    deploy: {
      how: 'The AI-automated factory runs hotter, so you need to complete the task faster — but since your city built the Mega Data Center, the AI\'s suggested completion time is 4 minutes 30 seconds instead of 4 minutes. The team may ask the Auditor to cut one rope of their choice.',
      how_zh: '由于使用了 AI 建筑系统，你们需要更快完成任务。但因为你们的城市建造了超级数据中心（Mega Data Center），AI 建议的完成时间是 4 分 30 秒（而非 4 分钟）。队伍可以请审计员（Auditor）剪断其中一条绳子。',
      scoreSheet: 'Untangled by time mark: 100% = 20 pts · 75% = 15 · 50% = 10 · 25% = 5 · less = 0.',
      scoreSheet_zh: '100%=20 分 | 75%=15 分 | 50%=10 分 | 25%=5 分 | <25%=0 分。',
    },
    reject: {
      how: 'Management allows more time to complete the task — 5 minutes to untangle, giving the team more time for teamwork and discussion.',
      how_zh: '没有使用 AI 建筑系统时，管理层会提供更多时间来完成任务。有 5 分钟时间解开，队伍有更多时间进行团队合作与讨论。',
      scoreSheet: 'Untangled by time mark: 100% = 20 pts · 75% = 15 · 50% = 10 · 25% = 5 · less = 0.',
      scoreSheet_zh: '100%=20 分 | 75%=15 分 | 50%=10 分 | 25%=5 分 | <25%=0 分。',
    },
    payout: [
      { result: '100% untangled (20 pts)', gain: '+2 Energy chips' },
      { result: '75% untangled (15 pts)', gain: '+1 Energy chip' },
      { result: 'Below 75%', gain: 'No chips' },
    ],
  },
]
